### ISSUE TITLE
Uncaught TypeError: Cannot read property of skater

### ISSUE THREAD

**Issue by kajtielplu** [AdamSmasherDerby/CRG-To-Statsbook#11]
when loading a JSON from scoreboard 5.0.5 (i think) into the data tool in both ubuntu 22.04 and windows 10 i get the following error:
![image](https://user-images.githubusercontent.com/69696660/187440168-3207120a-beab-4851-ae78-a5e412d4528d.png)
i have attached the JSON.
[crg-dataset-2022-08-30_202530.zip](https://github.com/AdamSmasherDerby/CRG-To-Statsbook/files/9452877/crg-dataset-2022-08-30_202530.zip)

**Comment by AdamSmasherDerby** [comment]
As CRG Scoreboard 5 now natively supports statsbook export, this program is now obsolete.  It will continue to be supported for users of CRG 3 and 4, but will not be updated to support 5.

**Comment by AdamSmasherDerby** [comment]
Good morning! Since CRG version 5 can export directly to a statsbook by itself, I have not updated this software for version 5, nor do I intend to.Thanks for supporting the software up until now!Sent from my Galaxy
-------- Original message --------From: kajtielplu ***@***.***> Date: 8/30/22  5:50 AM  (GMT-08:00) To: AdamSmasherDerby/CRG-To-Statsbook ***@***.***> Cc: Subscribed ***@***.***> Subject: [AdamSmasherDerby/CRG-To-Statsbook] Uncaught TypeError: Cannot read
  property of skater (Issue #11) 
when loading a JSON from scoreboard 5.0.5 (i think) into the data tool in both ubuntu 22.04 and windows 10 i get the following error:

i have attached the JSON.
crg-dataset-2022-08-30_202530.zip
