### ISSUE TITLE
Tool fails silently with data from a particular game

### ISSUE THREAD

**Issue by Weicocu** [AdamSmasherDerby/CRG-To-Statsbook#7]
We had an event recently with 4 scrimmages in one day. I wanted to dump out statsbooks since it seemed like the easiest way to let players see how they did.

Three of the games went through this tool nicely, but one just doesn't work, and doesn't give any sort of error. This was everyone's first time with 4.0 and several NSOs first time period, so odds are we did something wacky and there's something weird about the resulting JSON. But the lack of any sort of feedback makes it hard to tell. 

I attached the JSONs that are giving me this trouble, in case it's helpful.

[junior rookie game JSONs.zip](https://github.com/AdamSmasherDerby/CRG-To-Statsbook/files/4173636/junior.rookie.game.JSONs.zip)

Edit: to clarify, I don't think you should necessarily change the program to work for this scrimmage. But it might be worth checking why it's failing in case it's something that might come up in a real game. And failing silently seems less than ideal no matter how ridiculous our game was or how badly we might have screwed up the scoreboard settings.

**Comment by official-sounding** [comment]
ran the json file with devtools enabled, looks like the error is from period 1, jam 2.  Root Cause appears to be that Jammer was not set for the home team on this jam.

1. Fix this specific error to be more resilient (index.js line 639, though there are other references to jammerList[0] when jammerList is empty in this case)
2. Add some better error reporting to make it easier for users to tell there are errors

Does it make sense to record some of these cases as issues in this tool, or is the idea that the Statsbook Checker will catch those issues, so it adds too much complexity to report on here?
